name: afofa
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  equatable: ^2.0.3
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
